name: CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - uses: ludeeus/action-shellcheck@2.0.0
        with:
          scandir: .github/workflows/scripts/
          severity: error
