name: release
on:
  push:
    tags:
      - 'v*'

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        run: gh release create ${{ github.ref }} -t ${{ github.ref }} -n "Release ${{ github.ref }}" -F CHANGELOG.md

  release:
    runs-on: ubuntu-latest
    needs: create_release
    strategy:
      matrix:
        dir:
          - ce.hashima
          - empty.hashima
          - main.hashima
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: 'true'
        
      - run: git lfs pull

      - name: Zip ${{ matrix.dir }}
        run: zip -r ${{ matrix.dir }}.zip ${{ matrix.dir }}

      - name: Upload ${{ matrix.dir }}
        run: gh release upload ${{ github.ref }} ${{ matrix.dir }}.zip

  areamap:
    runs-on: ubuntu-latest
    needs: create_release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: 'true'
        
      - run: git lfs pull

      - name: Upload Area Flags
        run: gh release upload ${{ github.ref }} main.hashima/areaflags.map
