name: release
on:
  push:
    tags:
      - 'v*'

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Release
        run: |
          gh release create ${{ github.ref_name }} \
            -t ${{ github.ref_name }} \
            -n "Release ${{ github.ref_name }}"

  release:
    runs-on: ubuntu-latest
    needs: create_release
    strategy:
      fail-fast: false
      matrix:
        dir:
          - ce.hashima
          - empty.hashima
          - main.hashima
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: 'true'
        
      - run: git lfs pull

      - name: Zip ${{ matrix.dir }}
        run: zip -r ${{ matrix.dir }}.zip ${{ matrix.dir }}

      - name: Upload ${{ matrix.dir }}
        run: gh release upload ${{ github.ref_name }} ${{ matrix.dir }}.zip

  release_areaflags:
    runs-on: ubuntu-latest
    needs: create_release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: 'true'
        
      - run: git lfs pull

      - name: Upload Area Flags
        run: gh release upload ${{ github.ref_name }} main.hashima/areaflags.map

      - name: Hash Area Flags
        run: sha256sum main.hashima/areaflags.map > main.hashima/areaflags.map.sha256

      - name: Upload Hash
        run: gh release upload ${{ github.ref_name }} main.hashima/areaflags.map.sha256

